apiVersion: batch/v1
kind: Job
metadata:
  name: copyfail-mutator
  namespace: <NAMESPACE>
  labels:
    app: copyfail-repro
    role: mutator
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: copyfail-repro
        role: mutator
    spec:
      restartPolicy: Never
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: copyfail-repro
                  role: observer
              topologyKey: kubernetes.io/hostname
      containers:
        - name: mutator
          image: ghcr.io/emirkmo/copyfk8s-poc:mutator-ubuntu24.04
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
